### ISSUE TITLE
Request for clarification, user feedback

### ISSUE THREAD

**Issue by madrouin** [ACTRIS-CCRES/raw2l1#32]
In GitLab by @zeeman on Nov 29, 2022, 14:16

The `raw2l1` tool has been very helpful in preparing opportunities for cooperation on data from a network of remote sensing systems operated for ERC program <i>urbisphere</i>. **Thanks for sharing!** I have accumulated minor feedback that may not justify individual issues. This is primarily a request for clarification, and secondary a usage report.

1. Could you perhaps clarify the use of the input argument 'date'? The coordinates in the time dimension of the output file match the range of time found in the input files, which includes time stamps outside of the period suggested by 'date'. Are additional settings needed to activate validation for output to match 'date'? Is this planned to be implemented?
2. For a first time users it may not be immediately clear that `raw2l1` works very well with python 3.x. The document `prerequisites.rst`, once compiled from the source, lists python 2.7 as a requirement. However, using the pip `requirements.txt` file in a python 2.7 environment currently fails. I suggest to update the documentation, it would give new users a much better experience. 
3. In the current (v3.1.4) CL61 reader configuration example, both \$integer\$ and \$int\$ are used as placeholders. Is this intentional? According to log files, the \$int\$ placeholder is undefined and defaults to a float. 
4. The 'history' attribute can be set in a configuration file, but this is overwritten during runtime. https://gitlab.in2p3.fr/ipsl/sirta/raw2l1/-/blob/v3.1.4/raw2l1/tools/create_netcdf.py#L150-152
5. Have you considered using NetCDF compression (zlib) for variables in the NetCDF output?
6. In our case, a wrapper was needed around `raw2l1`, which updates configuration files and executes the `raw2l1` command. This in turn required a separate python environment (conda) for `raw2l1`: 
```yaml
### Conda requiremnts file, based on `raw2l1` v3.1.4 requirements.txt for pip.
name: sirta38v1

channels:
 - conda-forge
 
dependencies:
 - python=3.8
 - netCDF4=1.5.7
 - numpy=1.19
 - pytest=6.2.4
 - nose=1.3.7
 - pydocstyle=6.1.1
 - flake8=3.8.3
 - pytest-cov=2.12.1
 - black=19.10b0
 - sphinx=4.0
 - ipython # optional

 ##### PIP
 - pip
 - pip:
   - sphinx-rtd-theme==0.5.2
   - ipynb # optional
```
This environment supports `raw2l1`, directly from the command line or as subprocess from python, using:
```bash
conda run -n sirta38v1 python raw2l1.py <options> ....
```
